baseURL: https://back.hitback.space
languageCode: en-us
title: BACK 4U
languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 1
  zh:
    contentDir: content/chinese
    languageName: Chinese
    weight: 2

theme: paper
publishdir: ./site/
